name: Build ZOMG JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -o zomg-ultimate.zip -d .

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle (SDKMAN)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          echo "GRADLE_HOME=$HOME/.sdkman/candidates/gradle/current" >> $GITHUB_ENV
          echo "$HOME/.sdkman/candidates/gradle/current/bin" >> $GITHUB_PATH

      - name: Build
        run: gradle build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: zomg-jar
          path: build/libs/*.jar
